name: Node CI

on:
  push:
  pull_request:

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: make install

      - run: make lint

      - run: make test

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        with:
          debug: true
          coverageCommand: 'npm test -- --coverage'
          coverageLocations: 'coverage/lcov.info'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
